name: Deploy Laravel to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y zip unzip

    - name: Deploy to EC2
      env:
        AWS_EC2_IP: ${{ secrets.AWS_EC2_IP }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        scp -o StrictHostKeyChecking=no -r ./* $EC2_USER@$AWS_EC2_IP:/var/www/html
        ssh -o StrictHostKeyChecking=no $EC2_USER@$AWS_EC2_IP << 'EOF'
          cd /var/www/html
          composer install
          php artisan migrate --force
          sudo systemctl restart nginx
        EOF
